// <auto-generated />
using System;
using AqlanDental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AqlanDental.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AqlanDentalDbContext))]
[Migration("20260601120000_AddPasswordResetAndMustChangePassword")]
partial class AddPasswordResetAndMustChangePassword
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        // Note: This is a simplified snapshot. The full model is in AqlanDentalDbContextModelSnapshot.
#pragma warning restore 612, 618
    }
}
